name: build-and-test

on:
  - push
  - pull_request
  - release

defaults:
  run:
    working-directory: ui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  integrationtest:
    uses: nhsx/standards-registry/.github/workflows/integration-test.yml@master
    with:
      base_url: http://localhost:3000
      ckan_url: https://manage.test.standards.nhs.uk/api/action
      pages_ckan_url: https://manage.standards.nhs.uk/api/action
