on:
  workflow_call:
    inputs:
      base_url:
        description: 'The ui url, e.g. https://dev.standards.nhs.uk'
        required: true
        type: string
      recursive:
        description: Whether or not to recur through all URLs on all reachable pages (can take a while)
        required: false
        type: boolean
        default: false

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        continue-on-error: true
        with:
          # Required:
          url: ${{ inputs.base_url }}
          # optional:
          honorRobotExclusions: false
          ignorePatterns: 'github,google'
          recursiveLinks: ${{ inputs.recursive }}

      - name: Recover link checker result
        run: echo "${{steps.link-report.outputs.result}}"

      - name: Create Issue From File
        if: steps.link-report.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report for ${{ inputs.base_url }}
          content-filepath: ${{steps.link-report.outputs}}
          labels: report, automated issue
