on:
  workflow_call:
    inputs:
      base_url:
        description: 'The ui url, e.g. https://dev.standards.nhs.uk'
        required: true
        type: string
      fail:
        description: Whether or not the test should fail when it exists with non-0
        required: false
        type: boolean
        default: false
      local:
        description: Run tests against a local instance of the ui
        required: false
        type: boolean
        default: false

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v3

      - name: Run local copy of UI
        if: ${{ inputs.local }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - run: npm ci
      - run: npm run build --if-present

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: ${{ inputs.fail }}
          args: ${{ inputs.base_url }} --verbose --format detailed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
