name: notify-fail

on:
  workflow_run:
    branches:
      - master
    workflows:
      - build-and-test
      - deploy-dev
      - deploy-test
      - deploy-prod
    types:
      - completed
    conclusion:
      - failure

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: failbot
          SLACK_CHANNEL: developers
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://i.pinimg.com/originals/24/e4/35/24e435f2b98abc26385bef1cf1243d6f.png
          SLACK_MESSAGE: $GITHUB_REF
