name: Post deploy link checker

on:
  workflow_run:
    branches:
      - master
    workflows:
      - deploy-dev
      - deploy-test
      - deploy-prod
    types:
      - completed
    conclusion:
      - success

jobs:
  notify:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Echo things
        run: |
          echo github.ref_name ${{github.ref_name}}
          echo ${{github.event}}
          echo ${{steps}}
